apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-06-16T06:03:21Z"
    generation: 1
    labels:
      app: webapp
      pod-template-hash: 754bcc647d
    name: webapp-754bcc647d
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: cdb436aa-c940-4cc4-8b9b-241a972b1366
    resourceVersion: "1676"
    uid: 68a9c940-c595-44b5-a409-c543b4109d06
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: 754bcc647d
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: 754bcc647d
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 1
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
