apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
  name: static-busybox
spec:
  containers:
    - image: busybox
      name: static-busybox
      command: ["sleep"]
      args: ["1000"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
