apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-avior
spec:
  containers:
    - image: redis:alpine
      name: redis
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}