apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-avior
spec:
  containers:
    - image: nginx
      name: us-pv
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
