apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
    - image: nginx
      name: alpha
      resources: {}
      env:
        - name: name
          value: "alpha"
    - image: busybox
      name: beta
      resources: {}
      env:
        - name: name
          value: "beta"
      command: ["sleep"]
      args: ["4800"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}